Fix: verify tag

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,13 +20,12 @@ jobs:
 
       - name: Ensure tag is from prod branch
         run: |
-          TAG_COMMIT=$(git rev-list -n 1 $GITHUB_REF_NAME)
-          PROD_COMMIT=$(git rev-parse origin/prod)
+            git fetch origin prod
 
-          if [ "$TAG_COMMIT" != "$PROD_COMMIT" ]; then
-            echo "Tag is not on prod branch. Aborting release."
-            exit 1
-          fi
+            if ! git merge-base --is-ancestor "$GITHUB_SHA" origin/prod; then
+              echo "Tag is not reachable from prod branch. Aborting release."
+              exit 1
+            fi
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
